# Generated by Django 5.0.1 on 2026-02-15 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_hash', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phone_verifications',
            },
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_encrypted', models.TextField()),
                ('national_id_hash', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('billing_address', models.TextField()),
                ('id_front_photo', models.ImageField(upload_to='verifications/id_front/')),
                ('id_back_photo', models.ImageField(upload_to='verifications/id_back/')),
                ('selfie_photo', models.ImageField(upload_to='verifications/selfie/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_verifications',
            },
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('SELLER_SUBMITTED', 'Submitted'), ('SELLER_APPROVED', 'Approved'), ('SELLER_REJECTED', 'Rejected'), ('ADMIN_VIEWED', 'Viewed')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_verification_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
