# Generated by Django 5.0.1 on 2026-02-15 11:17

import common.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_avatar_user_ban_reason_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateprofile',
            name='national_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='privateprofile',
            name='national_id',
            field=models.CharField(db_index=True, help_text='14-digit Egyptian National ID', max_length=14, unique=True, validators=[common.validators.validate_egyptian_national_id]),
        ),
        migrations.AlterField(
            model_name='privateprofile',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Egyptian mobile number (e.g., 01012345678)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Egyptian mobile number (e.g., 01012345678)', regex='^(010|011|012|015)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='username',
            field=models.CharField(db_index=True, help_text='3-50 characters. Letters, numbers, underscores, and hyphens only.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-50 characters and contain only letters, numbers, underscores, and hyphens', regex='^[a-zA-Z0-9_-]{3,50}$'), common.validators.validate_username_not_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Max size: 5MB. Allowed formats: JPEG, PNG, GIF, WebP', null=True, upload_to='avatars/', validators=[common.validators.FileSizeValidator(max_size_mb=5), common.validators.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'image/webp'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('SUPPORT', 'Support')], db_index=True, default='BUYER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='privateprofile',
            index=models.Index(fields=['phone_number'], name='accounts_pr_phone_n_39d86b_idx'),
        ),
        migrations.AddIndex(
            model_name='privateprofile',
            index=models.Index(fields=['national_id'], name='accounts_pr_nationa_4d140f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicprofile',
            index=models.Index(fields=['username'], name='accounts_pu_usernam_b58fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_banned'], name='accounts_us_is_bann_a64a6d_idx'),
        ),
    ]
