# Generated by Django 5.0.1 on 2026-02-16 12:53

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_privateprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateprofile',
            name='national_id',
            field=models.CharField(db_index=True, help_text='National ID or Passport Number (5-20 alphanumeric characters)', max_length=20, unique=True, validators=[common.validators.validate_national_id]),
        ),
        migrations.AlterField(
            model_name='privateprofile',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='International phone number with country code (e.g., +1234567890)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +1234567890)', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
