# Generated by Django 5.0.1 on 2026-02-15 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('CHANGE_ROLE', 'Change User Role'), ('VIEW_SENSITIVE_DATA', 'View Sensitive Data'), ('APPROVE_VERIFICATION', 'Approve Verification'), ('REJECT_VERIFICATION', 'Reject Verification'), ('DELETE_USER', 'Delete User'), ('MODIFY_USER', 'Modify User')], db_index=True, max_length=30)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'db_table': 'admin_action_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin_user', 'timestamp'], name='admin_actio_admin_u_a0bce6_idx'), models.Index(fields=['target_user', 'timestamp'], name='admin_actio_target__2b155e_idx'), models.Index(fields=['action'], name='admin_actio_action_3e4d3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email used in login attempt', max_length=255)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('TOKEN_REFRESH', 'Token Refresh'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=20)),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure (if applicable)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User (null for failed login attempts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Log',
                'verbose_name_plural': 'Authentication Logs',
                'db_table': 'auth_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'timestamp'], name='auth_log_email_ba83b9_idx'), models.Index(fields=['ip_address', 'timestamp'], name='auth_log_ip_addr_b919ec_idx'), models.Index(fields=['action', 'success'], name='auth_log_action_e439f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MULTIPLE_FAILED_LOGINS', 'Multiple Failed Logins'), ('UNUSUAL_ACCESS_PATTERN', 'Unusual Access Pattern'), ('BANNED_USER_ATTEMPT', 'Banned User Access Attempt'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('INVALID_TOKEN', 'Invalid Token Usage'), ('SUSPICIOUS_FILE_UPLOAD', 'Suspicious File Upload')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('details', models.JSONField(default=dict, help_text='Details about the suspicious activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False, help_text='Whether the issue has been investigated/resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_suspicious_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User involved (if known)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Activity Log',
                'verbose_name_plural': 'Suspicious Activity Logs',
                'db_table': 'suspicious_activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['activity_type', 'severity'], name='suspicious__activit_fa3c7f_idx'), models.Index(fields=['ip_address', 'timestamp'], name='suspicious__ip_addr_6e1f2e_idx'), models.Index(fields=['resolved', 'severity'], name='suspicious__resolve_e1f754_idx')],
            },
        ),
    ]
